from merits.csvs_zip.csv_hierarchy import CsvTable, CsvHierarchy
from merits.edifact.definition_model import Node, Definition, Segment, Config
from merits.skdupd.csv_model import (
    Meta, Train, Por, Relation, Odi
)

EDIFACT_FILE_NAME = "SKDUPD.r"
"Default EDIFACT file name."

META_FILE_NAME = "meta.csv"
ODI_FILE_NAME = "SKDUPD_ODI.csv"
RELATION_FILE_NAME = "SKDUPD_RELATION.csv"
POR_FILE_NAME = "SKDUPD_POR.csv"
TRAIN_FILE_NAME = "SKDUPD_TRAIN.csv"
CSV_ZIP_FILE_NAME = "SKDUPD.zip"
"Default zipped CSVs file name."


def get_csv_hierarchy() -> CsvHierarchy:
    """
    Gives the definition of the hierarchy of CSV files for SKDUPD.
    :return:
    """
    meta_table = CsvTable.from_dataclass(META_FILE_NAME, Meta)
    train_table = CsvTable.from_dataclass(TRAIN_FILE_NAME, Train)
    por_table = CsvTable.from_dataclass(POR_FILE_NAME, Por, train_table)
    relation_table = CsvTable.from_dataclass(RELATION_FILE_NAME, Relation, por_table)
    odi_table = CsvTable.from_dataclass(ODI_FILE_NAME, Odi, train_table)
    csv_hierarchy = CsvHierarchy(
        csv_table_list=[
            meta_table,
            train_table,
            por_table,
            relation_table,
            odi_table,
        ],
        meta_file_name=META_FILE_NAME,
    )
    return csv_hierarchy


edifact_definition = Definition(
    version="4.1",
    structure=Node(
        name="root",
        node_id="root",
        occurrences_min=1,
        occurrences_max=1,
        child_list=[
            Node(
                name="UIB",
                node_id="0000",
                occurrences_min=1,
                occurrences_max=1
            ),
            Node(
                name="UIH",
                node_id="0010",
                occurrences_min=1,
                occurrences_max=1
            ),
            Node(
                name="MSD",
                node_id="0020",
                occurrences_min=1,
                occurrences_max=1
            ),
            Node(
                name="ORG",
                node_id="0030",
                occurrences_min=1,
                occurrences_max=1
            ),
            Node(
                name="HDR",
                node_id="0040",
                occurrences_min=1,
                occurrences_max=1
            ),
            Node(
                name="IFT",
                node_id="0050",
                occurrences_min=0,
                occurrences_max=1
            ),
            Node(
                name="RFR",
                node_id="0060",
                occurrences_min=0,
                occurrences_max=9
            ),
            Node(
                name="1_ERI",
                node_id="0070",
                occurrences_min=0,
                occurrences_max=99,
                child_list=[
                    Node(
                        name="ERI",
                        node_id="0080",
                        occurrences_min=1,
                        occurrences_max=1
                    ),
                    Node(
                        name="RFR",
                        node_id="0090",
                        occurrences_min=0,
                        occurrences_max=1
                    ),
                    Node(
                        name="IFT",
                        node_id="0100",
                        occurrences_min=0,
                        occurrences_max=1
                    )
                ]
            ),
            Node(
                name="2_PRD",
                node_id="0110",
                occurrences_min=1,
                occurrences_max=99999,
                child_list=[
                    Node(
                        name="PRD",
                        node_id="0120",
                        occurrences_min=1,
                        occurrences_max=1
                    ),
                    Node(
                        name="PDT",
                        node_id="0130",
                        occurrences_min=0,
                        occurrences_max=3
                    ),
                    Node(
                        name="IFT",
                        node_id="0140",
                        occurrences_min=0,
                        occurrences_max=9
                    ),
                    Node(
                        name="TRF",
                        node_id="0150",
                        occurrences_min=0,
                        occurrences_max=9
                    ),
                    Node(
                        name="ASD",
                        node_id="0160",
                        occurrences_min=0,
                        occurrences_max=99
                    ),
                    Node(
                        name="MSD",
                        node_id="0170",
                        occurrences_min=0,
                        occurrences_max=1
                    ),
                    Node(
                        name="RFR",
                        node_id="0180",
                        occurrences_min=0,
                        occurrences_max=9
                    ),
                    Node(
                        name="3_SER",
                        node_id="0190",
                        occurrences_min=0,
                        occurrences_max=99,
                        child_list=[
                            Node(
                                name="SER",
                                node_id="0200",
                                occurrences_min=1,
                                occurrences_max=1
                            ),
                            Node(
                                name="ASD",
                                node_id="0210",
                                occurrences_min=0,
                                occurrences_max=1
                            )
                        ]
                    ),
                    Node(
                        name="4_POP",
                        node_id="0220",
                        occurrences_min=0,
                        occurrences_max=999,
                        child_list=[
                            Node(
                                name="POP",
                                node_id="0230",
                                occurrences_min=1,
                                occurrences_max=1
                            ),
                            Node(
                                name="PDT",
                                node_id="0240",
                                occurrences_min=0,
                                occurrences_max=3
                            ),
                            Node(
                                name="IFT",
                                node_id="0250",
                                occurrences_min=0,
                                occurrences_max=1
                            ),
                            Node(
                                name="TRF",
                                node_id="0260",
                                occurrences_min=0,
                                occurrences_max=9
                            ),
                            Node(
                                name="ASD",
                                node_id="0270",
                                occurrences_min=0,
                                occurrences_max=99
                            ),
                            Node(
                                name="FRQ",
                                node_id="0280",
                                occurrences_min=0,
                                occurrences_max=9
                            ),
                            Node(
                                name="5_SER",
                                node_id="0290",
                                occurrences_min=0,
                                occurrences_max=99,
                                child_list=[
                                    Node(
                                        name="SER",
                                        node_id="0300",
                                        occurrences_min=1,
                                        occurrences_max=1
                                    ),
                                    Node(
                                        name="ASD",
                                        node_id="0310",
                                        occurrences_min=0,
                                        occurrences_max=1
                                    )
                                ]
                            ),
                            Node(
                                name="6_DTI",
                                node_id="0320",
                                occurrences_min=0,
                                occurrences_max=99,
                                child_list=[
                                    Node(
                                        name="DTI",
                                        node_id="0330",
                                        occurrences_min=1,
                                        occurrences_max=1
                                    ),
                                    Node(
                                        name="IFT",
                                        node_id="0340",
                                        occurrences_min=0,
                                        occurrences_max=9
                                    )
                                ]
                            ),
                            Node(
                                name="7_POR",
                                node_id="0350",
                                occurrences_min=0,
                                occurrences_max=999,
                                child_list=[
                                    Node(
                                        name="POR",
                                        node_id="0360",
                                        occurrences_min=1,
                                        occurrences_max=1
                                    ),
                                    Node(
                                        name="MES",
                                        node_id="0370",
                                        occurrences_min=0,
                                        occurrences_max=1
                                    ),
                                    Node(
                                        name="ASD",
                                        node_id="0380",
                                        occurrences_min=0,
                                        occurrences_max=9
                                    ),
                                    Node(
                                        name="SER",
                                        node_id="0390",
                                        occurrences_min=0,
                                        occurrences_max=9
                                    ),
                                    Node(
                                        name="TRF",
                                        node_id="0400",
                                        occurrences_min=0,
                                        occurrences_max=1
                                    ),
                                    Node(
                                        name="8_RFR",
                                        node_id="0410",
                                        occurrences_min=0,
                                        occurrences_max=99,
                                        child_list=[
                                            Node(
                                                name="RFR",
                                                node_id="0420",
                                                occurrences_min=1,
                                                occurrences_max=1
                                            ),
                                            Node(
                                                name="RLS",
                                                node_id="0430",
                                                occurrences_min=0,
                                                occurrences_max=1
                                            ),
                                            Node(
                                                name="TCE",
                                                node_id="0440",
                                                occurrences_min=0,
                                                occurrences_max=9
                                            )
                                        ]
                                    )
                                ]
                            ),
                            Node(
                                name="9_ODI",
                                node_id="0450",
                                occurrences_min=0,
                                occurrences_max=99,
                                child_list=[
                                    Node(
                                        name="ODI",
                                        node_id="0460",
                                        occurrences_min=1,
                                        occurrences_max=1
                                    ),
                                    Node(
                                        name="PDT",
                                        node_id="0470",
                                        occurrences_min=0,
                                        occurrences_max=1
                                    ),
                                    Node(
                                        name="IFT",
                                        node_id="0480",
                                        occurrences_min=0,
                                        occurrences_max=1
                                    ),
                                    Node(
                                        name="TRF",
                                        node_id="0490",
                                        occurrences_min=0,
                                        occurrences_max=1
                                    ),
                                    Node(
                                        name="TFF",
                                        node_id="0500",
                                        occurrences_min=0,
                                        occurrences_max=1
                                    ),
                                    Node(
                                        name="ASD",
                                        node_id="0510",
                                        occurrences_min=0,
                                        occurrences_max=1
                                    ),
                                    Node(
                                        name="10_SER",
                                        node_id="0520",
                                        occurrences_min=0,
                                        occurrences_max=99,
                                        child_list=[
                                            Node(
                                                name="SER",
                                                node_id="0530",
                                                occurrences_min=1,
                                                occurrences_max=1
                                            ),
                                            Node(
                                                name="ASD",
                                                node_id="0540",
                                                occurrences_min=0,
                                                occurrences_max=1
                                            )
                                        ]
                                    )
                                ]
                            )
                        ]
                    )
                ]
            ),
            Node(
                name="UIT",
                node_id="0550",
                occurrences_min=1,
                occurrences_max=1
            ),
            Node(
                name="UIZ",
                node_id="0600",
                occurrences_min=1,
                occurrences_max=1
            ),
        ]
    ),
    segment_list=[
        Segment(
            node_id="0000",
            format="""
            UIB
            +syntax_identifier=UNOB
                    :syntax_version_number=4 
                    :
                    :
            +initiator
                    :
                    :
                    :
            +
                    :
                    :
            +scenario_id=TITAN
                    :scenario_version
                    :scenario_release
                    :controlling_agency_1=ER
            +dialogue_id
                    :dialogue_version
                    :dialogue_release
                    :controlling_agency_2=ER
            +interchange_sender_id
                    :id_code_qualifier_1=X001
                    :
                    :
            +interchange_recipient_id
                    :id_code_qualifier_2=X001
                    :
                    :
            +event_date
                    :event_time
                    :
            +
            +test_indicator"""
        ),
        Segment(
            node_id="0010",
            format="""
            UIH
            +message_type=SKDUPD
                    :message_version=D
                    :message_release=04A
                    :
                    :controlling_agency=UN
                    :
            +sequence_number
            +initiator
                    :
                    :
                    :
            +
                    :
                    :
            +
                    :
                    :
            +"""
        ),
        Segment(
            node_id="0020",
            format="""
            MSD
            +business_function_code=AAR
                    :message_function_code=61
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :
            +
            +
                    :
                    :"""
        ),
        Segment(
            node_id="0030",
            format="""
            ORG
            +message_provider
                    :
                    :
            +
                    :
                    :
                    :
            +
                    :
                    :
                    :
            +timetable_provider
            +
            +
                    :
                    :
            +"""
        ),
        Segment(
            node_id="0040",
            format="""
            HDR
            +status_description_code=81
            +validity_code=273
                    :validity
                    :
                    :
                *qualifier_code_1
                    :date_1
                    :
                    :
                *qualifier_code_2
                    :date_2
                    :
                    :
            +reference_number
            +free_text
            +
            +language_code"""
        ),
        Segment(
            node_id="0050",
            format=""
        ),
        Segment(
            node_id="0060",
            format="""
            RFR
            +reference_function_code=AGX
                    :reference_id
                    :
                    :
                    :"""
        ),
        Segment(
            node_id="0080",
            format=""
        ),
        Segment(
            node_id="0090",
            format=""
        ),
        Segment(
            node_id="0100",
            format="""
            IFT
            +text_subject_code=AAO
                    :
                    :
                    :
                    :langague_code
            +error_description"""
        ),
        Segment(
            node_id="0120",
            format="""
            PRD
            +service_number
                    :reservation
                    :tariff
                    :service_mode
                    :
                    :
                    :service_name
            +service_provider
                *information_provider
                *reservation_company"""
        ),
        Segment(
            node_id="0130",
            format="""
            PDT
            +
            +
                    :
                    :
                    :service_brand
                    :
                    :
                    :"""
        ),
        Segment(
            node_id="0140",
            format="""
            IFT
            +text_subject_code
                    :
                    :
                    :
                    :language_code
            +description"""
        ),
        Segment(
            node_id="0150",
            format=""
        ),
        Segment(
            node_id="0160",
            format="""
            ASD
            +asd_code
                    :first_time
                    :last_time
                    :
                    :
                    :
                    :
                    :reservation
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :frequency
                    :unit
            +period_qualifier=273
                    :period_of_validity
                    :
                    :days
            +weekdays"""
        ),
        Segment(
            node_id="0170",
            format="""
            MSD
            +business_function_code=AAR
                    :message_function_code=56
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :
            +
            +
                    :
                    :"""
        ),
        Segment(
            node_id="0180",
            format="""
            RFR
            +reference_function_code=AVI
                    :second_service_number
                    :
                    :
                    :"""
        ),
        Segment(
            node_id="0200",
            format="""
            SER
            +ser_code
                    :
                    :
                    :reservation
            +
            +units_quantity
            +period_qualifier=273
                    :period_of_validity
                    :
                    :days
            +weekdays"""
        ),
        Segment(
            node_id="0210",
            format="""
            ASD
            +asd_code
                    :first_time
                    :last_time
                    :
                    :
                    :
                    :
                    :reservation
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :frequency
                    :unit
            +period_qualifier=273
                    :period_of_validity
                    :
                    :days
            +weekdays"""
        ),
        Segment(
            node_id="0230",
            format="""
            POP
            +period_qualifier=273
                    :first_day_last_day
                    :
                    :days
            +weekdays
            +"""
        ),
        Segment(
            node_id="0240",
            format="""
            PDT
            +
            +reservation
                    :
                    :
                    :brand_code
                    :
                    :
                    :tariff"""
        ),
        Segment(
            node_id="0250",
            format="""
            IFT
            +text_subject_code=ADU
                    :
                    :
                    :
                    :language_code
            +special_notes"""
        ),
        Segment(
            node_id="0260",
            format=""
        ),
        Segment(
            node_id="0270",
            format="""
            ASD
            +asd_code
                    :first_time
                    :last_time
                    :
                    :
                    :
                    :
                    :reservation
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :frequency
                    :unit
            +period_qualifier=273
                    :period_of_validity
                    :
                    :days
            +weekdays"""
        ),
        Segment(
            node_id="0280",
            format="""
            FRQ
            +frequency_interval
                    :unit
                    :first_last_time
                    :"""
        ),
        Segment(
            node_id="0300",
            format="""
            SER
            +ser_code
                    :
                    :
                    :reservation
            +
            +units_quantity
            +period_qualifier=273
                    :period_of_validity
                    :
                    :days
            +weekdays"""
        ),
        Segment(
            node_id="0310",
            format="""
            ASD
            +asd_code
                    :first_time
                    :last_time
                    :
                    :
                    :
                    :
                    :reservation
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :frequency
                    :unit
            +period_qualifier=273
                    :period_of_validity
                    :
                    :days
            +weekdays"""
        ),
        Segment(
            node_id="0330",
            format="""
            DTI
            +date_time_period_qualifier
                    :date_time_period
                    :
                    :
            +
                    :"""
        ),
        Segment(
            node_id="0340",
            format="""
            IFT
            +text_subject_code=BLO
                    :
                    :
                    :
                    :language_code
            +special_day_description"""
        ),
        Segment(
            node_id="0360",
            format="""
            POR
            +uic
                    :type_stop
                    :responsible_agency
                    :
            +arrival
                    :
                    :
                    :arrival_offset
                *departure
                    :
                    :
                    :departure_offset
            +arrival_platform
                    :
                *departure_platform
                    :
            +location_qualifier
            +"""
        ),
        Segment(
            node_id="0370",
            format="""
            MES
            +distance
                    :unit
                    :
                    :"""
        ),
        Segment(
            node_id="0380",
            format="""
            ASD
            +asd_code
                    :first_time
                    :last_time
                    :
                    :
                    :
                    :
                    :reservation
                    :first_location
                    :
                    :
                    :
                    :
                    :second_location
                    :
                    :frequency
                    :unit
            +period_qualifier=273
                    :period_of_validity
                    :
                    :days
            +weekdays"""
        ),
        Segment(
            node_id="0390",
            format=""
        ),
        Segment(
            node_id="0400",
            format="""
            TRF
            +trf_code
                    :
                    :
                    :"""
        ),
        Segment(
            node_id="0420",
            format="""
            RFR
            +reference_function_code=AUE
                    :service_number
                    :
                    :
                    :service_provider"""
        ),
        Segment(
            node_id="0430",
            format="""
            RLS
            +relation_type_code=13
            +relation
                    :
                    :
                    :"""
        ),
        Segment(
            node_id="0440",
            format="""
            TCE
            +transfer_time
            +certainty
                    :certainty_description
                    :language_code
                    :"""
        ),
        Segment(
            node_id="0460",
            format="""
            ODI
            +from_stop
                *to_stop
            +from_stop_number
                *to_stop_number"""
        ),
        Segment(
            node_id="0470",
            format="""
            PDT
            +
            +reservation
                    :
                    :
                    :brand_code
                    :
                    :
                    :tariff"""
        ),
        Segment(
            node_id="0480",
            format=""
        ),
        Segment(
            node_id="0490",
            format="""
            TRF
            +traffic_restriction
                    :
                    :
                    :"""
        ),
        Segment(
            node_id="0500",
            format="""
            TFF
            +tff_code
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :
            +
                    :
                    :
                    :
                    :
            +charge_unit_code
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :"""
        ),
        Segment(
            node_id="0510",
            format="""
            ASD
            +asd_code
                    :first_time
                    :last_time
                    :
                    :
                    :
                    :
                    :reservation
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :frequency
                    :unit
            +period_qualifier=273
                    :period_of_validity
                    :
                    :days
            +weekdays"""
        ),
        Segment(
            node_id="0530",
            format="""
            SER
            +ser_code
                    :
                    :
                    :reservation
            +
            +units_quantity
            +period_qualifier=273
                    :period_of_validity
                    :
                    :days
            +weekdays"""
        ),
        Segment(
            node_id="0540",
            format="""
            ASD
            +asd_code
                    :first_time
                    :last_time
                    :
                    :
                    :
                    :
                    :reservation
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :frequency
                    :unit
            +period_qualifier=273
                    :period_of_validity
                    :
                    :days
            +weekdays"""
        ),
        Segment(
            node_id="0550",
            format="""
            UIT
            +message_reference
            +number_of_segments"""
        ),
        Segment(
            node_id="0600",
            format="""
            UIZ
            +initiator
                    :
                    :
                    :
            +number_of_messages
            +"""
        ),

    ],
    config=Config(),
)
