from merits.csvs_zip.csv_hierarchy import CsvHierarchy, CsvTable
from merits.edifact.definition_model import Definition, Node, Config, Segment
from merits.tsdupd.csv_model import Meta, Stop, Synonym, Mct, Footpath

EDIFACT_FILE_NAME = "TSDUPD.r"
"Default EDIFACT file name."

META_FILE_NAME = "meta.csv"
STOP_FILE_NAME = "TSDUPD_STOP.csv"
SYNONYM_FILE_NAME = "TSDUPD_SYNONYM.csv"
MCT_FILE_NAME = "TSDUPD_MCT.csv"
FOOTPATH_FILE_NAME = "TSDUPD_FOOTPATH.csv"
CSV_ZIP_FILE_NAME = "TSDUPD.zip"
"Default zipped CSVs file name."


def get_csv_hierarchy() -> CsvHierarchy:
    """
    Gives the definition of the hierarchy of CSV files for TSDUPD.
    :return:
    """
    meta_table = CsvTable.from_dataclass(META_FILE_NAME, Meta)
    stop_table = CsvTable.from_dataclass(STOP_FILE_NAME, Stop)
    synonym_table = CsvTable.from_dataclass(SYNONYM_FILE_NAME, Synonym, stop_table)
    mct_table = CsvTable.from_dataclass(MCT_FILE_NAME, Mct, stop_table)
    footpath_table = CsvTable.from_dataclass(FOOTPATH_FILE_NAME, Footpath, stop_table)
    csv_hierarchy = CsvHierarchy(
        csv_table_list=[
            meta_table,
            stop_table,
            synonym_table,
            mct_table,
            footpath_table,
        ],
        meta_file_name=META_FILE_NAME,
    )
    return csv_hierarchy


edifact_definition = Definition(
    version="4.1",
    structure=Node(
        name="root",
        node_id="root",
        occurrences_min=1,
        occurrences_max=1,
        child_list=[
            Node(
                name="UIB",
                node_id="0000",
                occurrences_min=1,
                occurrences_max=1
            ),
            Node(
                name="UIH",
                node_id="0010",
                occurrences_min=1,
                occurrences_max=1
            ),
            Node(
                name="MSD",
                node_id="0020",
                occurrences_min=1,
                occurrences_max=1
            ),
            Node(
                name="ORG",
                node_id="0030",
                occurrences_min=0,
                occurrences_max=1
            ),
            Node(
                name="HDR",
                node_id="0040",
                occurrences_min=0,
                occurrences_max=1
            ),
            Node(
                name="IFT",
                node_id="0050",
                occurrences_min=0,
                occurrences_max=9
            ),
            Node(
                name="RFR",
                node_id="0060",
                occurrences_min=0,
                occurrences_max=1
            ),
            Node(
                name="CNY",
                node_id="0070",
                occurrences_min=0,
                occurrences_max=1
            ),
            Node(
                name="TIZ",
                node_id="0080",
                occurrences_min=0,
                occurrences_max=1
            ),
            Node(
                name="LNG",
                node_id="0090",
                occurrences_min=0,
                occurrences_max=1
            ),
            Node(
                name="1_ERI",
                node_id="0100",
                occurrences_min=0,
                occurrences_max=99,
                child_list=[
                    Node(
                        name="ERI",
                        node_id="0110",
                        occurrences_min=1,
                        occurrences_max=1,
                    ),
                    Node(
                        name="RFR",
                        node_id="0120",
                        occurrences_min=0,
                        occurrences_max=1,
                    ),
                    Node(
                        name="IFT",
                        node_id="0130",
                        occurrences_min=0,
                        occurrences_max=1,
                    ),
                ],
            ),
            Node(
                name='2_ALS',
                node_id='0140',
                occurrences_min=1,
                occurrences_max=99999,
                child_list=[
                    Node(
                        name="ALS",
                        node_id="0150",
                        occurrences_min=1,
                        occurrences_max=1
                    ),
                    Node(
                        name="ADS",
                        node_id="0160",
                        occurrences_min=0,
                        occurrences_max=1
                    ),
                    Node(
                        name="POP",
                        node_id="0170",
                        occurrences_min=0,
                        occurrences_max=9
                    ),
                    Node(
                        name="CON",
                        node_id="0180",
                        occurrences_min=0,
                        occurrences_max=1
                    ),
                    Node(
                        name="TRF",
                        node_id="0190",
                        occurrences_min=0,
                        occurrences_max=1
                    ),
                    Node(
                        name="CNY",
                        node_id="0200",
                        occurrences_min=0,
                        occurrences_max=1
                    ),
                    Node(
                        name="TIZ",
                        node_id="0210",
                        occurrences_min=0,
                        occurrences_max=1
                    ),
                    Node(
                        name="LNG",
                        node_id="0220",
                        occurrences_min=0,
                        occurrences_max=1
                    ),
                    Node(
                        name="SER",
                        node_id="0230",
                        occurrences_min=0,
                        occurrences_max=1
                    ),
                    Node(
                        name="IFT",
                        node_id="0240",
                        occurrences_min=0,
                        occurrences_max=9
                    ),
                    Node(
                        name="3_ASD",
                        node_id='0250',
                        occurrences_min=0,
                        occurrences_max=99,
                        child_list=[
                            Node(
                                name="ASD",
                                node_id="0260",
                                occurrences_min=1,
                                occurrences_max=1
                            ),
                            Node(
                                name="CON",
                                node_id="0270",
                                occurrences_min=0,
                                occurrences_max=1
                            ),
                        ]
                    ),
                    Node(
                        name="4_PRD",
                        node_id='0280',
                        occurrences_min=0,
                        occurrences_max=99,
                        child_list=[
                            Node(
                                name="PRD",
                                node_id="0290",
                                occurrences_min=1,
                                occurrences_max=1
                            ),
                            Node(
                                name="SER",
                                node_id="0300",
                                occurrences_min=0,
                                occurrences_max=1
                            ),
                            Node(
                                name="FRQ",
                                node_id="0310",
                                occurrences_min=0,
                                occurrences_max=1
                            ),
                            Node(
                                name="IFT",
                                node_id="0320",
                                occurrences_min=0,
                                occurrences_max=1
                            ),
                            Node(
                                name="POR",
                                node_id="0330",
                                occurrences_min=0,
                                occurrences_max=1
                            ),
                        ]
                    ),
                    Node(
                        name="5_RFR",
                        node_id='0340',
                        occurrences_min=0,
                        occurrences_max=99,
                        child_list=[
                            Node(
                                name="RFR",
                                node_id="0350",
                                occurrences_min=1,
                                occurrences_max=1
                            ),
                            Node(
                                name="MES",
                                node_id="0360",
                                occurrences_min=0,
                                occurrences_max=1
                            ),
                            Node(
                                name="RLS",
                                node_id="0370",
                                occurrences_min=0,
                                occurrences_max=1
                            ),
                            Node(
                                name="6_PRD",
                                node_id='0380',
                                occurrences_min=0,
                                occurrences_max=99,
                                child_list=[
                                    Node(
                                        name="PRD",
                                        node_id="0390",
                                        occurrences_min=1,
                                        occurrences_max=1
                                    ),
                                    Node(
                                        name="POP",
                                        node_id="0400",
                                        occurrences_min=0,
                                        occurrences_max=1
                                    ),
                                    Node(
                                        name="SER",
                                        node_id="0410",
                                        occurrences_min=0,
                                        occurrences_max=1
                                    ),
                                ]
                            ),
                        ]
                    ),
                ]
            ),
            Node(
                name="7_NME",
                node_id='0420',
                occurrences_min=0,
                occurrences_max=999,
                child_list=[
                    Node(
                        name="NME",
                        node_id="0430",
                        occurrences_min=1,
                        occurrences_max=1,
                    ),
                    Node(
                        name="ADS",
                        node_id="0440",
                        occurrences_min=0,
                        occurrences_max=1,
                    ),
                    Node(
                        name="CON",
                        node_id="0450",
                        occurrences_min=0,
                        occurrences_max=1,
                    ),
                    Node(
                        name="8_RFR",
                        node_id='0460',
                        occurrences_min=0,
                        occurrences_max=99,
                        child_list=[
                            Node(
                                name="RFR",
                                node_id="0470",
                                occurrences_min=1,
                                occurrences_max=1,
                            ),
                            Node(
                                name="RLS",
                                node_id="0480",
                                occurrences_min=0,
                                occurrences_max=1,
                            ),
                        ]),
                ]),
            Node(
                name="UIT",
                node_id="0490",
                occurrences_min=1,
                occurrences_max=1,
            ),
            Node(
                name="UIZ",
                node_id="0600",
                occurrences_min=1,
                occurrences_max=1,
            ),
        ],
    ),
    segment_list=[
        Segment(
            node_id="0000",
            format="""
            UIB
            +syntax_identifier=UNOB
                    :syntax_version_number=4 
                    :
                    :
            +initiator
                    :
                    :
                    :
            +
                    :
                    :
            +scenario_id=TITAN
                    :scenario_version
                    :scenario_release
                    :controlling_agency_1=ER
            +dialogue_id
                    :dilaogue_version
                    :dialogue_release
                    :controlling_agency_2=ER
            +interchange_sender_id
                    :id_code_qualifier_1=X001
                    :
                    :
            +interchange_recipient_id
                    :id_code_qualifier_2=X001
                    :
                    :
            +event_date
                    :event_time
                    :
            +
            +test_indicator"""
        ),
        Segment(
            node_id="0010",
            format="""
            UIH
            +message_type=TSDUPD
                    :message_version=D
                    :message_release=04A
                    :
                    :controlling_agency=UN
                    :
            +sequence_number
            +initiator
                    :
                    :
                    :
            +
                    :
                    :
            +
                    :
                    :
            +"""
        ),
        Segment(
            node_id="0020",
            format="""
            MSD
            +business_function_code=AAR
                    :message_function_code=61
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :
            +
            +
                    :
                    :"""
        ),
        Segment(
            node_id="0030",
            format="""
            ORG
            +message_provider
                    :
                    :
            +
                    :
                    :
                    :
            +
                    :
                    :
                    :
            +location_provider
            +
            +
                    :
                    :
            +"""
        ),
        Segment(
            node_id="0040",
            format="""
            HDR
            +status_description_code=81
            +validity_code=273
                    :validity
                    :
                    :
                *qualifier_code_1
                    :date_1
                    :
                    :
                *qualifier_code_2
                    :date_2
                    :
                    :
            +reference_number
            +free_text
            +
            +language_code"""
        ),
        Segment(
            node_id="0050",
            format=""
        ),
        Segment(
            node_id="0060",
            format="""
            RFR
            +reference_function_code=AGX
                    :reference_id
                    :
                    :
                    :"""
        ),
        Segment(
            node_id="0070",
            format="""
            CNY
            +country_code
            +qualifier_code_1
                    :summer_time
                    :
                    :
                *qualifier_code_2
                    :winter_time
                    :
                    :
            +summer_variation
                *winter_variation
            +currency_code
            +language_code"""
        ),
        Segment(
            node_id="0080",
            format="""
            TIZ
            +time_zone
                    :time_variation"""
        ),
        Segment(
            node_id="0090",
            format="""
            LNG
            +language_qualifier
            +language_code
                    :"""
        ),
        Segment(
            node_id="0110",
            format="""
            ERI
            +error_code
                    :
                    :"""
        ),
        Segment(
            node_id="0120",
            format="""
            RFR
            +reference_function_code=AWL
                    :reference_id
                    :
                    :
                    :"""
        ),
        Segment(
            node_id="0130",
            format="""
            IFT
            +text_subject_code=AAO
                    :
                    :
                    :
                    :langague_code
            +error_description"""
        ),
        Segment(
            node_id="0150",
            format="""
            ALS
            +location_function_code
            +uic_code
                    :location_name
                    :
                    :
            +latitude
            +longitude"""
        ),
        Segment(
            node_id="0160",
            format="""
            ADS
            +
                    :address_type_code=1
                    :address_status_code=2
            +address_format_code=5
            +address_description
                    :
                    :
                    :
                    :
            +city_name
            +postcode
            +country_name_code
            +
                    :
                    :
                    :
            +
                    :
                    :
                    :"""
        ),
        Segment(
            node_id="0170",
            format="""
            POP
            +period_qualifier
                    :first_day_last_day
                    :
                    :
            +weekdays
            +"""
        ),
        Segment(
            node_id="0180",
            format="""
            CON
            +qualifier_code
                    :contact
                    :contact_type_code
                    :
                    :"""
        ),
        Segment(
            node_id="0190",
            format="""
            TRF
            +traffic_restriction_code
                    :
                    :
                    :"""
        ),
        Segment(
            node_id="0200",
            format="""
            CNY
            +country_code
            +qualifier_code_1
                    :summer_time
                    :
                    :
                *qualifier_code_2
                    :winter_time
                    :
                    :
            +summer_variation
                *winter_variation
            +currency_code
            +language_code"""
        ),
        Segment(
            node_id="0210",
            format="""
            TIZ
            +time_zone
                    :time_variation"""
        ),
        Segment(
            node_id="0220",
            format="""
            LNG
            +language_qualifier
            +language_code
                    :"""
        ),
        Segment(
            node_id="0230",
            format="""
            SER
            +ser_code
                    :
                    :
                    :
            +
            +
            +
                    :
                    :
                    :
            +"""
        ),
        Segment(
            node_id="0240",
            format="""
            IFT
            +text_subject_code
                    :
                    :
                    :
                    :language_code
            +location_name"""
        ),
        Segment(
            node_id="0260",
            format="""
            ASD
            +asd_code
                    :first_time
                    :last_time
                    :
                    :
                    :
                    :
                    :
                    :fisrt_location
                    :
                    :
                    :
                    :
                    :
                    :
                    :
                    :
            +period_qualifier=273
                    :period_of_validity
                    :
                    :
            +weekdays"""
        ),
        Segment(
            node_id="0270",
            format="""
            CON
            +qualifier_code=HN
                    :contact
                    :contact_type_code
                    :
                    :"""
        ),
        Segment(
            node_id="0290",
            format="""
            PRD
            +
                    :
                    :
                    :service_mode_or_brand_1
                    :service_mode_or_brand_2
                    :
                    :mct
            +service_provider_1
                *service_provider_2"""
        ),
        Segment(
            node_id="0300",
            format=""
        ),
        Segment(
            node_id="0310",
            format=""
        ),
        Segment(
            node_id="0320",
            format=""
        ),
        Segment(
            node_id="0330",
            format=""
        ),
        Segment(
            node_id="0350",
            format="""
            RFR
            +reference_function_code
                    :uic_code
                    :
                    :
                    :"""
        ),
        Segment(
            node_id="0360",
            format="""
            MES
            +transfer_time
                    :unit=MIN
                    :
                    :"""
        ),
        Segment(
            node_id="0370",
            format="""
            RLS
            +relation_type_code=13
            +relation
                    :
                    :
                    :"""
        ),
        Segment(
            node_id="0390",
            format="""
            PRD
            +
                    :
                    :
                    :service_mode_or_brand_1
                    :service_mode_or_brand_2
                    :
                    :
            +service_provider_1
                *service_provider_2"""
        ),
        Segment(
            node_id="0400",
            format="""
            POP
            +period_qualifier
                    :period
                    :
                    :
            +weekdays
            +"""
        ),
        Segment(
            node_id="0410",
            format="""
            SER
            +ser_code
                    :
                    :
                    :
            +
            +
            +
                    :
                    :
                    :
            +"""
        ),
        Segment(
            node_id="0430",
            format="""
            NME
            +qualifier_code=DDO
                    :provider_name
                    :provider_code
                    :"""
        ),
        Segment(
            node_id="0440",
            format="""
            ADS
            +
                    :address_type_code=1
                    :address_status_code=2
            +address_format_code=5
            +address_description
                    :
                    :
                    :
                    :
            +city_name
            +postcode
            +country_name_code
            +
                    :
                    :
                    :
            +
                    :
                    :
                    :"""
        ),
        Segment(
            node_id="0450",
            format="""
            CON
            +qualifier_code=HN
                    :contact
                    :contact_type_code
                    :
                    :"""
        ),
        Segment(
            node_id="0470",
            format="""
            RFR
            +reference_function_code=AWO
                    :reference_id
                    :
                    :
                    :"""
        ),
        Segment(
            node_id="0480",
            format="""
            RLS
            +relation_type_code=13
            +relation
                    :
                    :
                    :"""
        ),
        Segment(
            node_id="0490",
            format="""
            UIT
            +message_reference
            +number_of_segments"""
        ),
        Segment(
            node_id="0600",
            format="""
            UIZ
            +initiator
                    :
                    :
                    :
            +number_of_messages
            +"""
        ),
    ],
    config=Config(),
)
